<a href="https://colab.research.google.com/github/pgordin/OptDisc2024/blob/main/Grafy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów

In [ ]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [ ]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is not None) and (len(vertices)==n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

In [ ]:
def print_graph(graph):
  """
   Wypisuje na ekranie graf podany jako lista sąsiedztwa (słownik pythona)
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Tworzenie i modyfikacje grafów

In [ ]:
def add_vertex(graph, vertex):
  """
  Nowy wierzchołek do istniejącego grafu
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje nowy łuk (podany jako para wierzchołków) do istniejącego grafu
  Rozważamy grafy proste, skierowane
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Dodaje nową krawędź (podaną jako para wierzchołków) do istniejącego grafu
  traktując graf nieskierowany jako prosty graf skierowany, symetryczni i bez pętli
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


# Przykłady wykorzystania

In [ ]:
vertices = ["a", "b", "c", "d", "e", "f"]
matrix = np.array([[0,1,1,0,0,0],[1,0,0,1,1,0],[1,0,0,0,0,1],[0,1,0,0,0,1],[0,1,0,0,0,0],[0,0,1,1,0,0]])
print(vertices)
print(matrix)
print("-------------------------")
print_matrix(vertices, matrix)
print("-------------------------")
print_matrix(None, matrix)


['a', 'b', 'c', 'd', 'e', 'f']
[[0 1 1 0 0 0]
 [1 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 1 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 0 0]]
-------------------------
a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d
-------------------------
1 :  2  3
2 :  1  4  5
3 :  1  6
4 :  2  6
5 :  2
6 :  3  4


Druga reprezentacja

In [ ]:
graph = {
  'a' : ['b',  'c'],
  'b' : ['a', 'd', 'e'],
  'c' : ['a', 'f'],
  'd' : ['b', 'f'],
  'e' : ['b'],
  'f' : ['c', 'd'],
  'g' : []
}
print(graph)
print("--------------------")
print_graph(graph)

{'a': ['b', 'c'], 'b': ['a', 'd', 'e'], 'c': ['a', 'f'], 'd': ['b', 'f'], 'e': ['b'], 'f': ['c', 'd'], 'g': []}
--------------------
a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d
g :


In [ ]:
add_vertex(graph, "h")
print_graph(graph)

a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d
g :
h :


In [ ]:
add_arc(graph, ["g", "h"])
print_graph(graph)

a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d
g :  h
h :


In [ ]:
add_edge(graph, ["g", "h"])
print_graph(graph)

a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d
g :  h
h :  g


In [ ]:
add_edge(graph, ["g", "g"])

ValueError: Pętla!

In [ ]:
add_edge(graph, ["h", "f"])
add_edge(graph, ["h", "i"])
print_graph(graph)

a :  b  c
b :  a  d  e
c :  a  f
d :  b  f
e :  b
f :  c  d  h
g :  h
h :  g  f  i
i :  h


## Tworzenie grafów losowych $G(n, p)$

In [ ]:
# dla powtarzalności
seed(2024)

In [ ]:
#losuje graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, [i, j])

print_graph(random_graph)

1 :  5  10
2 :  3  5  9  10
3 :  2  8
4 :  6  7  8  10
5 :  1  2  10
6 :  4  8  10
7 :  4  9  10
8 :  3  4  6
9 :  2  7
10 :  1  2  4  5  6  7
