<a href="https://colab.research.google.com/github/pgordin/OptDisc2024/blob/main/lab1%20-%20programowanie%20liniowe%20(ci%C4%85g%C5%82e%20i%20dyskretne)%20-%20SciPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zadanie 1
Na przykładzie ciągłego problemu plecakowego sprawdzić (i przetestować) SciPy, PuLP i Google OR-Tools.

In [1]:
from scipy.optimize import linprog
import numpy as np
c = [-20, -15, -10, -5, -30, -18]
A=np.eye(6)
A=np.append(A, np.ones(6).reshape(1,6),0)
b=[3.5, 2, 3, 5, 1, 2.5, 10]

print(A)
print(b)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[3.5, 2, 3, 5, 1, 2.5, 10]


In [2]:
lp=linprog(c=c, A_ub=A, b_ub=b, bounds=(0,None), method='simplex')
lp

<ipython-input-2-4c80090c967e>:1: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  lp=linprog(c=c, A_ub=A, b_ub=b, bounds=(0,None), method='simplex')


 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: -185.0
       x: [ 3.500e+00  2.000e+00  1.000e+00  0.000e+00  1.000e+00
            2.500e+00]
     nit: 13

In [3]:
lp.fun*(-1)

185.0

In [4]:
lp.x

array([3.5, 2. , 1. , 0. , 1. , 2.5])

# Zadanie 2
Jak wygląda programowanie całkowitoliczbowe w tych pakietach? Rozwiązać (zwykły) problem plecakowy.

In [5]:
x1_bounds = (0, 1)
x2_bounds = (0, 3)
x3_bounds = (0, 5)
x4_bounds = (0, 1)
x5_bounds = (0, 5)
x6_bounds = (0, 2)

c = [-5000, -1500, -200, -1000, -500, -600]
A=[[1, 0.5, 0.3, 4, 1, 3]]
b=[11.5]

lp=linprog(c=c, A_ub=A, b_ub=b, bounds=[x1_bounds, x2_bounds, x3_bounds, x4_bounds, x5_bounds,x6_bounds], method='highs', integrality=1)
lp

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -13200.0
              x: [ 1.000e+00  3.000e+00  3.000e+00  0.000e+00  5.000e+00
                   1.000e+00]
            nit: -1
          lower:  residual: [ 1.000e+00  3.000e+00  3.000e+00  0.000e+00
                              5.000e+00  1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          upper:  residual: [ 0.000e+00  0.000e+00  2.000e+00  1.000e+00
                              0.000e+00  1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.000e-01]
                 marginals: [ 0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -13200.0
        mip_gap: 0.0

In [6]:
lp.fun*(-1)

13200.0

In [7]:
lp.x

array([1., 3., 3., 0., 5., 1.])

# Maximum Transversal

## With Binary Matrix

In [8]:
import numpy as np
from scipy.optimize import linear_sum_assignment

In [9]:
def find_maximum_transversal(bm):
    bm = -bm
    row_idx, col_idx = linear_sum_assignment(bm)
    transversal = list(zip(row_idx, col_idx))
    return transversal, row_idx, col_idx

In [10]:
mat = np.array([
    [4,1,6,2,3],
    [5,0,3,7,6],
    [2,3,4,5,8],
    [3,4,6,3,4],
    [4,6,5,8,6]
])

In [14]:
tr = find_maximum_transversal(mat)
tr[0]

[(0, 2), (1, 0), (2, 4), (3, 1), (4, 3)]

In [16]:
for idx in tr[0]:
    print(f"{idx}: {mat[idx]}")

(0, 2): 6
(1, 0): 5
(2, 4): 8
(3, 1): 4
(4, 3): 8
